apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: someaddress@somemail.com
    #https://acme-v02.api.letsencrypt.org/directory is for product environment
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: www-yourhost-tls
    # Add a single challenge solver
    solvers:
    - http01:
        ingress:
          name: "www-app-ingress"
      selector:
        dnsZones:
        - 'youhost.com'
